### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by VinSpee** [codingalchemy/chronic#1]
This seems really awesome, and I'd love to dig in a bit more, but the examples are insignificant. I'd love to see some more complex examples if possible - a "seed" project would be even better i think.

I'm thinking something like this:
- bundle with browserify (bundle splitting would be awesome)
- compile css with some preprocessor (I'm partial to postcss)
- minify js and css
- optimize images
  -spin up a static dev server (using something like browser-sync)
  -watch for changes

How could something like this be accomplished? I'm pretty unclear on getting even a basic browserify example to build.
##### ./tool/bundle.js

```
var browserify = require('browserify');
var source     = require('vinyl-transform');

module.exports = function(t) {
    var b = browserify();
    b.add(source(t.path[0]));

    t.build(b.bundle(), t.dest());
}
```
##### ./tool/index.js

```
var chron = require('chronic');
var concat = require('gulp-concat');

chron('default', chron.once('bundle'));

chron('bundle', chron.once('concat')
    .path('./app/scripts/**/*.js')
    .dest('./ex-test.js'),
    require('./bundle.js'));
```
##### ./app/scripts/ex.js

```
console.log('dude');
```

I run `node tool`.

result:

```
  default  Running...
  bundle   Running...
```

but no file gets written.

What am I getting wrong?

**Comment by RnbWd** [comment]
A few things to note about your example: 
- `b.add(source('./app/scripts/**/*.js'))`, is the output of `b.add(source(t.path[0]));`
- `t.dest` or `vinyl.dest` expects a folder destination, see gulp's [docs](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpdestpath-options)
- the 'concat' task doesn't exist - it needs to be explicitly defined as `chron('concat', ...)`, so your build is waiting for the 'concat' to finish, stalling indefinitely. Using `chron.once` is equivalent to the array in  `gulp.task('bundle', ['concat'])`

The setup you're _probably_ looking for is like this:

``` js
var browserify = require('browserify');
chron('bundle', chron
    .path('./app/scripts/ex-test.js')
    .dest('./dest'),
   function(t) {
     var b = browserify();
     b.add(t.path[0]);
     t.build(b.bundle(), t.source('bundle.js'), t.dest());
   });
```

`vinyl-source-stream` is included in the library now, and it's used to pipe files between browserify and gulp, `vinyl-transform` is a different plugin. Using `t.build` is equivalent to this:

``` js
 var source = require('vinyl-source-stream');
 var b = browserify();
 b.add('./app/scripts/ex-test.js');
 b.bundle()
   .pipe(source('bundle.js'))
   .pipe(gulp.dest('./dest')
```

I'll try to post some examples later today. I do have local builds bundling browserfy and pre-processing css, minifying js, etc.. 

I'd actually recommend using `chronic` just like gulp at first, you could write something like this and it work the same:

``` js
chron('bundle', function(t) {
 var b = browserify()
 b.add('file')
 b.bundle().pipe(source('bundle')).pipe(t.dest('output'))
});
```

But to chain tasks, `t.done` must be called, so you could add `.on('close', t.done)` or wrap it in `t.eos(.., t.done)`, `t.eos` is end-of-stream. It's whatever, I could define a few more ways to do it all. The flexibility is what i'm going for, use it how you feel most comfortable :)

**Comment by VinSpee** [comment]
Awesome. I will get digging on this - thanks for the help.

**Comment by RnbWd** [comment]
Added an example repo here - https://github.com/codingalchemy/chronic-seed
