### ISSUE TITLE
Error catching pattern

### ISSUE THREAD

**Issue by VinSpee** [codingalchemy/chronic#2]
I kind of understand this:

> ## chronic.build
> 
> returns `function(t) with pump(t.src(), -> [transforms], -> t.dest())`, returning t.done upon completion or >error

but what's a good pattern for catching and reporting errors when using `t.build`?

**Comment by RnbWd** [comment]
I just updated the repo to log errors if one occurs. Whether or not the error will destroy the process is dependent on the 3rd party library (same thing with gulp). This should log errors for using chronic.build (where you have no choice of error handling). If you're using `t.build` or `t.pump` inside of a function, then you could do this:

``` js
// for t.build

var one = blah().on('error', console.log)
var two = two().on('error',console.log)
var dest = t.dest()
t.build(t.src(),one,two,dest);


// or for t.pump

t.pump(t.src(), one(), two(), three(), t.dest(), function(err) {

if (err) console.log (err) // or throw or return if preferred
t.done()
})

```

**Comment by VinSpee** [comment]
💪💪 thanks!

**Comment by RnbWd** [comment]
NP :) 

`t.build` now logs errors automatically, so you don't have to manually do the `.on('error') error handling.If using`t.pump`you could pass err into (t.done(err)) and it will console log (which is identical to what`t.build` does).

**Comment by RnbWd** [comment]
Just wanted to clarify that the library should be logging errors right now without any change in code, but there are other ways if `console.log` isn't what'd needed.
