### ISSUE TITLE
Minification pattern

### ISSUE THREAD

**Issue by VinSpee** [codingalchemy/chronic#3]
What's a good pattern for minifying files?

I envision something like this happening:

```
chron('package', chron.once('build'), minify);
```

Ideally, that would fire off a function that goes through the `public/` dir and minifies the appropriate files accordingly. Does that make sense? or does it make sense to have the minification step in each file type's corresponding task and allow it to be flipped on with an env switch?

**Comment by RnbWd** [comment]
Is there an equivalent pattern in gulp? 

I think it's fine to minify files in `public/`, you could probably include all the minifiers in one task. The hardest part would be separating the files by type and applying the appropriate transform. I haven't tried this yet, but I think it's possible to have multiple vinyl streams (`t.src`) running parallel in one task (one for each minifier). ~~They could all be wrapped in `t.eos`:~~ It doesn't matter if the task calls t.done unless a subsequent task is dependent it finishing. 

``` js
// theory code
var mincss = t.src('public/*.css').pipe(...).pipe(t.dest('./public'));
var minjs = t.src('public/*.js').pipe(...).pipe(t.dest('./public/'));
...
```
