### ISSUE TITLE
Working with non-streamy modules

### ISSUE THREAD

**Issue by VinSpee** [codingalchemy/chronic#4]
Hey! Loving chronic so far.

I'm trying to use it with [StyleDoc](https://github.com/thybzi/styledoc), but I can't quite get it working. 

I assume that I need to wrap the styledoc task in something to make it streamable. Any ideas?

Here's where I'm at:
#### Setup:

```
var gutil    = require('gulp-util');
var reload   = require('browser-sync').reload;
var styledoc = require('styledoc');
var source   = require('vinyl-source-stream');

module.exports = function(t) {
  var dest = t.dest();
  var source = t.source(t.path[1])
  if (t.params.watch) {
    dest.pipe(reload({stream: true}));
  }
  var docGen = styledoc.showcaseFile(t.path[0], {
    page_title: 'projectologist',
    output_dir: t.path[1]
  }).done(function(){ done(true);}).fail(function(){done(false);});

  t.build(docGen, source, dest);
};

```
#### Error:

```
  styledoc  Running...

StyleDoc v0.0.7
Source CSS file:  ./dist/styles/main.css
Target directory: ./dist/

Loading source CSS...

/Users/vince/projects/projectologist/node_modules/chronic/node_modules/pump/index.js:23
        stream.on('close', function() {
               ^
TypeError: Object #<Object> has no method 'on'
    at destroyer (/Users/vince/projects/projectologist/node_modules/chronic/node_modules/pump/index.js:23:9)
    at /Users/vince/projects/projectologist/node_modules/chronic/node_modules/pump/index.js:67:10
    at Array.map (native)
    at pump (/Users/vince/projects/projectologist/node_modules/chronic/node_modules/pump/index.js:64:25)
    at build (/Users/vince/projects/projectologist/node_modules/chronic/lib/task.js:126:10)
    at Object.build (/Users/vince/projects/projectologist/node_modules/chronic/node_modules/new-struct/node_modules/methodify/index.js:22:19)
    at Object.module.exports [as fn] (/Users/vince/projects/projectologist/build/transforms/styledoc.js:17:5)
    at callTaskFn (/Users/vince/projects/projectologist/node_modules/chronic/lib/run.js:68:8)
    at /Users/vince/projects/projectologist/node_modules/chronic/lib/run.js:43:7
    at /Users/vince/projects/projectologist/node_modules/chronic/lib/run.js:91:5
```

Thanks so much for your work on this.

**Comment by RnbWd** [comment]
Thanks! It's def not perfect yet but I'm glad you're using it. 

I know what's up with the error - it happens whenever I pipe() something that's not a stream. In this case, there's no reason to stream. Just put `reload({stream: true}` and `t.done()` inside of `styledoc...)done(function(){ .. })` and the task should work fine. `t.build` isn't necessary, calling `t.done()` lets the task know it's finished and `styledoc` is already taking care of IO on it's own.

Two more things i noticed: -  `done(true)` shouldn't do anything unless `done` is defined somewhere else in the file, and I've included `require('vinyl-source-stream')` as `t.source` in chronic because I use it so often and I'm lazy :)

**Comment by RnbWd** [comment]
@VinSpee 

> I assume that I need to wrap the styledoc task in something to make it streamable. Any ideas?

Just to clarify, streaming isn't necessary. I use non-streaming modules all the time, [this](https://github.com/codingalchemy/chronic-seed/blob/master/build/transforms/del.js) example from chronic seed doesn't use any streams. However, there are ways to make non-streamable things streamable. [This](https://github.com/codingalchemy/chronic-seed/blob/master/build/transforms/es6to5.js) example shows how to tap into a gulp stream.

**Comment by VinSpee** [comment]
what if I want to go the non-streaming route, but need to get the file contents and name from t.src and t.path?

**Comment by RnbWd** [comment]
Before I implement any custom behavior like this, I look to see if a [gulp-plugin](http://gulpjs.com/plugins/) exists which will do the job for me. It doesn't appear that anyone has created a plugin for `styledoc` yet, so you'll have to do it manually. It's possible to create a styledoc plugin for gulp, but I like the DIY mentally.

My [second example](https://github.com/codingalchemy/chronic-seed/blob/master/build/transforms/es6to5.js) above is does this. The `gulp-6to5` plugin works almost identical to this module, but I wrote this example to show that plugins aren't necessary. This is how it works:

 `gulp-tap` is provides every `file` from `t.src()` in a [vinyl format](https://github.com/wearefractal/vinyl), one-file-at-a-time.`file.relative` is the name, `file.contents` is a buffer of it's contents (use `.toString()` if you need a string), and `file.path` gives you it's full path. By reassigning `file.contents` to the modified version, (`file.contents = new Buffer('hello')`, it'll pass the transformed file to the next pipe (or dest). Internally most gulp-plugins use the `through2` library for doing this, but `gulp-tap` is easier to use (under the hood does the same thing).

Another, less efficient way would be to use `globby`,with `t.path`, which gives you a list of all the file paths in an array. You could use [.., .., ..].forEach() on the array and get the file contents with the node's `fs` module, and push that content into an array or whatever. You could also use `stream-concat` and use some fs-streaming (once you have access to file paths), and `stream-concat`will output an array of all the file contents (might also work with t.src() but you'd get an array of vinyl's).

**Comment by VinSpee** [comment]
Awesome. Incredibly helpful. I ended up going with [Styledown](https://github.com/styledown/styledown) - like so:

```
module.exports = function(t) {
  var ext       = require('gulp-ext');
  var tap       = require('gulp-tap');
  var reload    = require('browser-sync').reload;

  var dest = t.dest();
  if (t.params.watch) {
    dest.pipe(reload({stream: true}));
  }
  t.build(t.src(), tap(docify), ext.replace('html'), dest);
}

function docify(file) {
  var Styledown = require('styledown');
  if(file.contents) {
    var opts = {
      inline: true
    };

    var currentFile = {
      name: file.relative,
      data: file.contents.toString()
    };

    var res = Styledown.parse([currentFile], opts)
    file.contents = Buffer(res, 'utf8');
  }
}
```

look reasonable?
